__all__ = ['GGA',
           'GSA',
           'GPS',
           'SPACE',
           'STATUS',
           'CHECK',
           'MESSAGE',
           'TALKER',
           'GEO',
           'SERIAL',
           'IPLIST',
           'XIM',
           'FEATURES',
           ]
