'''
Farmstar NMEA Talker alias dictionary
Retrieved from: http://freenmea.net/docs
'''

TALKER = {'VER':'NMEA-0183',
          'GL':'GLONASS Receiver',
          'GP':'Global Positioning System (GPS)',
          'AG':'Heading Track Controller (Autopilot) - General',
          'AP':'Heading Track Controller (Autopilot) - Magnetic',
          'AI':'Automatic Identification System',
          'CD':'Digital Selective Calling (DSC)',
          'CR':'Data Receiver',
          'CS':'Satellite',
          'CT':'Radio-Telephone (MF/HF)',
          'CV':'Radio-Telephone (VHF)',
          'CX':'Scanning Receiver',
          'DE':'DECCA Navigator',
          'DF':'Direction Finder',
          'EC':'Electronic Chart System (ECS)',
          'EI':'Electronic Chart Display & Information System (ECDIS)',
          'EP':'Emergency Position Indicating Beacon (EPIRB)',
          'ER':'Engine room Monitoring Systems',
          'GN':'Global Navigation Satellite System (GNSS)',
          'HC':'HEADING SENSORS: Compass, Magnetic',
          'HE':'Gyro, North Seeking',
          'HN':'Gyro, Non-North Seeking',
          'II':'Integrated Instrumentation',
          'IN':'Integrated Navigation',
          'LC':'Loran C',
          'P':'Proprietary Code',
          'RA':'Radar and/or Radar Plotting',
          'SD':'Sounder, depth',
          'SN':'Electronic Positioning System, other/general',
          'SS':'Sounder, scanning',
          'TI':'Turn Rate Indicator',
          'VD':'VELOCITY SENSORS: Doppler, other/general',
          'VM':'Speed Log, Water, Magnetic',
          'VW':'Speed Log, Water, Mechanical',
          'VR':'Voyage Data Recorder',
          'YX':'Transducer',
          'ZA':'TIMEKEEPERS, TIME/DATE: Atomic Clock',
          'ZC':'Chronometer',
          'ZQ':'Quartz',
          'ZV':'Radio Update',
          'WI':'Weather Instruments',
          }
          
