# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmstar_gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='UNIX',
            field=models.FloatField(),
        ),
    ]
